#!/bin/bash

echo "starting backup"
lftp -f ~/.bin/motog_backup.lftp

if [ $? -ne 0 ]; then
    echo "hmm, something somewhere went wrong. stay tuned spaceman"
else
    echo "all done, swim on sir"
fi
