#!/bin/bash

# quote file
quotefile="$HOME/org/quotes.org"
if ! [ -e $quotefile ]; then
    touch $quotefile
fi

# get primary selection
quote=`xclip -out -selection primary`

# write quote
echo -n "* " >> $quotefile
if [ $# -ge 1 ]; then
    echo $1 >> $quotefile
else
    echo "anonymous" >> $quotefile
fi

echo $quote >> $quotefile

