#!/bin/bash

# problems:
# the script needs to be run as root or with sudo, 
# otherwise cron doesn't accept the job in /etc/cron.d
# this makes it necesarry to set the path without the $HOME variable.

# check if root or sudo
if [ $UID -ne 0 ]; then
    echo "You need sudo powers for that."
    exit
fi

# activate seccam by writing the cronjob to the seccam file
if [ "$1" == "on" ]; then
    echo """SHELL=/bin/sh                                                                                

* * * * * jinn /home/jinn/.bin/sec_cam.sh""" > /etc/cron.d/seccam
    exit
fi

# deactivate by clearing the file
if [ ! -e /etc/cron.d/seccam ]; then
    echo "file doesn't exist"
    exit
fi

if [ "$1" == "off" ]; then
    echo "" >  /etc/cron.d/seccam
    exit
fi

# catch invalid argument
echo "usage: setseccam [on/off]"
